send_message:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to send the message from.
      required: true
      example: default
      selector:
        text:
    to:
      required: true
      example: 12025550123@s.whatsapp.net
      selector:
        text:
    body:
      required: true
      advanced: true
      selector:
        object:
    options:
      required: false
      advanced: true
      selector:
        object:

check_number:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    to:
      required: true
      example: "+12025550123"
      selector:
        text:

set_status:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    status:
      required: true
      example: Available
      selector:
        text:

presence_subscribe:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    userId:
      name: Target user ID
      description: The WhatsApp phone or LID JID to monitor.
      required: true
      example: 12025550123@s.whatsapp.net
      selector:
        text:

send_presence_update:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    type:
      required: true
      example: composing
      selector:
        select:
          options:
            - unavailable
            - available
            - composing
            - recording
            - paused
    to:
      required: false
      example: 12025550123@s.whatsapp.net
      selector:
        text:

send_infinity_presence_update:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    type:
      required: true
      example: composing
      selector:
        select:
          options:
            - unavailable
            - available
            - composing
            - recording
            - paused
    to:
      required: false
      example: 12025550123@s.whatsapp.net
      selector:
        text:

read_messages:
  fields:
    clientId:
      name: Client ID
      description: The add-on client session to use.
      required: true
      example: default
      selector:
        text:
    body:
      required: true
      example: >
        {"keys": {"id": "EXAMPLE_MESSAGE_ID", "remoteJid": "12025550123@s.whatsapp.net", "fromMe": false}}
      selector:
        object:
