name: WhatsappV2
version: "1.4.35"
slug: whatsapp_addon
description: WhatsApp Web bridge for Home Assistant actions and events
url: "https://github.com/moryoav/ha-addons/tree/main/whatsapp_addon"
homeassistant_api: true
hassio_api: true
ingress: true
ingress_entry: /
panel_icon: mdi:whatsapp
panel_title: WhatsApp
discovery:
  - whatsapp
arch:
  - aarch64
  - amd64
init: false
options:
  clients:
    - default
  log_level: info
schema:
  clients:
    - str
  log_level: list(info|debug)
  api_token: password?
