---
name: Hassfest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions: {}

jobs:
  validate-hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
